
package yeapp;

/**
 *
 * @author Dell
 */

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class proyecto extends javax.swing.JFrame {
    DefaultTableModel  modelo;    
    public static final String URL="jdbc:mysql://127.0.0.1:3306/proyecto";
    public static final String USUARIO="root";
    public static final String CONTRASENHA="1234";
    
    PreparedStatement insertar;

    public proyecto() {
        initComponents();
        esconder();
        modelo=new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Fecha");
        modelo.addColumn("Persona");
        modelo.addColumn("Carrera");
        modelo.addColumn("Número");
        
    }
     public void esconder(){
        fondo2.setVisible(false);
        leercontrol.setVisible(false);
        nombre.setVisible(false);
        fecha.setVisible(false);
        persona.setVisible(false);
        carrera.setVisible(false);
        numero.setVisible(false);
        guardar.setVisible(false);
        nombrec.setVisible(false);
        fechac.setVisible(false);
        personac.setVisible(false);
        carrerac.setVisible(false);
        numeroc.setVisible(false);
        limpiar.setVisible(false);
        fondo1.setVisible(false);
        base.setVisible(false);
   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicio = new javax.swing.JPanel();
        leercontrol = new javax.swing.JButton();
        nombre = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        persona = new javax.swing.JLabel();
        carrera = new javax.swing.JLabel();
        numero = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        nombrec = new javax.swing.JTextField();
        fechac = new javax.swing.JTextField();
        personac = new javax.swing.JTextField();
        carrerac = new javax.swing.JTextField();
        numeroc = new javax.swing.JTextField();
        limpiar = new javax.swing.JButton();
        fondo1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        base = new javax.swing.JButton();
        fondo2 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        titulo = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        administrador = new javax.swing.JLabel();
        fondo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leercontrol.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        leercontrol.setText("Base de datos");
        leercontrol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        leercontrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leercontrolActionPerformed(evt);
            }
        });
        inicio.add(leercontrol, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        nombre.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setText(" Nombre ");
        nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        inicio.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        fecha.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        fecha.setText("Fecha");
        fecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        inicio.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 90, -1));

        persona.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        persona.setForeground(new java.awt.Color(255, 255, 255));
        persona.setText("Persona");
        persona.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        inicio.add(persona, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 200, 100, -1));

        carrera.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        carrera.setForeground(new java.awt.Color(255, 255, 255));
        carrera.setText("Carrera");
        carrera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        inicio.add(carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 250, 90, -1));

        numero.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        numero.setForeground(new java.awt.Color(255, 255, 255));
        numero.setText("Número");
        numero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        inicio.add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 300, 100, -1));

        guardar.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        guardar.setText(" Guardar");
        guardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        inicio.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 150, -1));
        inicio.add(nombrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 110, 30));
        inicio.add(fechac, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 110, 30));
        inicio.add(personac, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 110, 30));
        inicio.add(carrerac, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 110, 30));
        inicio.add(numeroc, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 110, 30));

        limpiar.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        limpiar.setText("Limpiar");
        limpiar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        inicio.add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 150, -1));

        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yeapp/3.jpg"))); // NOI18N
        inicio.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 420));

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        base.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        base.setText("Base de datos");
        base.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        base.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                baseMouseClicked(evt);
            }
        });
        base.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baseActionPerformed(evt);
            }
        });
        jLayeredPane1.add(base, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 200, 70));

        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yeapp/2.jpeg"))); // NOI18N
        jLayeredPane1.add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 450));

        inicio.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 420));

        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Franklin Gothic Book", 0, 48)); // NOI18N
        titulo.setText("Control de inventarios");
        titulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jLayeredPane2.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        usuario.setFont(new java.awt.Font("Franklin Gothic Book", 0, 36)); // NOI18N
        usuario.setText("   Usuario");
        usuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuarioMouseClicked(evt);
            }
        });
        jLayeredPane2.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 200, 60));

        administrador.setBackground(new java.awt.Color(0, 0, 153));
        administrador.setFont(new java.awt.Font("Franklin Gothic Book", 0, 36)); // NOI18N
        administrador.setText(" Administrador");
        administrador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        administrador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                administradorMouseClicked(evt);
            }
        });
        jLayeredPane2.add(administrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 230, 60));

        fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yeapp/1.jpg"))); // NOI18N
        jLayeredPane2.add(fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 498, -1));

        inicio.add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leercontrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leercontrolActionPerformed
        try{
                Connection conectar = null;
                conectar = getConnection();
                
                PreparedStatement consulta;
                ResultSet resultado;
                
                consulta= (PreparedStatement) conectar.prepareStatement("SELECT * FROM inventario");
                resultado=consulta.executeQuery();
                
                if (resultado.next())
                {
                    JOptionPane.showMessageDialog(null, "Nombre: " + resultado.getString("nombre"));
                    JOptionPane.showMessageDialog(null, "Fecha: " + resultado.getString("fecha"));
                    JOptionPane.showMessageDialog(null, "Persona: " + resultado.getString("persona"));
                    JOptionPane.showMessageDialog(null, "Carrera: " + resultado.getString("carrera"));
                    JOptionPane.showMessageDialog(null, "Número: " + resultado.getString("número"));                  
                } 
                else
                {
                JOptionPane.showMessageDialog(null, "no existen datos");
                }
                conectar.close();
            }
            catch(Exception e){
                System.out.println(e);
            
            }
    }//GEN-LAST:event_leercontrolActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        Connection conectar = null;
         try{
                
                conectar = getConnection();
              
                             
                insertar=  (PreparedStatement) conectar.prepareStatement("INSERT INTO inventario(nombre,fecha,persona,carrera,número) VALUES(?,?,?,?,?)");
                insertar.setString(1, nombrec.getText());          
                insertar.setString(2, fechac.getText());
                insertar.setString(3, personac.getText());
                insertar.setString(4, carrerac.getText());
                insertar.setString(5, numeroc.getText());
                
                int respuesta=insertar.executeUpdate();
                
                if (respuesta > 0){
                   JOptionPane.showMessageDialog(null, "El equipo se ha ingresado correctamente");
                   limpiardatos();
                }else
                {
                JOptionPane.showMessageDialog(null, "error. Revisar formato");
                limpiardatos();
                }
                
               
                conectar.close();
            }
            catch(Exception e){
                System.out.println(e);
            
            }
    }//GEN-LAST:event_guardarActionPerformed
 private void limpiardatos()
    {
    nombrec.setText(null);
    fechac.setText(null);
    personac.setText(null);
    carrerac.setText(null);
    numeroc.setText(null);
    }
    private void usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioMouseClicked
        esconder();
        usuario.setVisible(false);
        administrador.setVisible(false);
        titulo.setVisible(false);
        fondo1.setVisible(false);
        fondo3.setVisible(false);
        base.setVisible(true);
        limpiar.setVisible(true);
        fondo2.setVisible(true);
        guardar.setVisible(false);
    }//GEN-LAST:event_usuarioMouseClicked

    private void administradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_administradorMouseClicked
        esconder();
        usuario.setVisible(false);
        administrador.setVisible(false);
        titulo.setVisible(false);
        fondo2.setVisible(false);
        fondo3.setVisible(false);
        nombre.setVisible(true);
        fecha.setVisible(true);
        persona.setVisible(true);
        carrera.setVisible(true);
        numero.setVisible(true);
        nombrec.setVisible(true);
        fechac.setVisible(true);
        personac.setVisible(true);
        carrerac.setVisible(true);
        numeroc.setVisible(true);
        fondo1.setVisible(true);
        guardar.setVisible(true);
        limpiar.setVisible(true);
        leercontrol.setVisible(true);
    }//GEN-LAST:event_administradorMouseClicked

    private void baseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baseActionPerformed

    private void baseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baseMouseClicked
       esconder();
        usuario.setVisible(false);
        administrador.setVisible(false);
        titulo.setVisible(false);
        fondo2.setVisible(true);
        fondo3.setVisible(false);
        nombre.setVisible(false);
        fecha.setVisible(false);
        persona.setVisible(false);
        carrera.setVisible(false);
        numero.setVisible(false);
        nombrec.setVisible(false);
        fechac.setVisible(false);
        personac.setVisible(false);
        carrerac.setVisible(false);
        numeroc.setVisible(false);
        fondo1.setVisible(false);
        guardar.setVisible(false);
        limpiar.setVisible(false);
        leercontrol.setVisible(true);
    }//GEN-LAST:event_baseMouseClicked

 
 public static Connection getConnection(){
    
            Connection conectar = null;
            
            try{
                Class.forName("com.mysql.jdbc.Driver");
                conectar = (Connection)DriverManager.getConnection(URL,USUARIO,CONTRASENHA);
                JOptionPane.showMessageDialog(null, "CONEXION REALIZADA");
            }
            catch(Exception e){
                System.out.println(e);            
            }            
        return conectar;
    }
 

 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new proyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel administrador;
    private javax.swing.JButton base;
    private javax.swing.JLabel carrera;
    private javax.swing.JTextField carrerac;
    private javax.swing.JLabel fecha;
    private javax.swing.JTextField fechac;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel fondo3;
    private javax.swing.JButton guardar;
    private javax.swing.JPanel inicio;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JButton leercontrol;
    private javax.swing.JButton limpiar;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField nombrec;
    private javax.swing.JLabel numero;
    private javax.swing.JTextField numeroc;
    private javax.swing.JLabel persona;
    private javax.swing.JTextField personac;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
